# Generated by Django 4.1 on 2024-09-11 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('studio', 'Студия'), ('one_room', 'Однокомнатная'), ('two_room', 'Двухкомнатная'), ('three_room', 'Трехкомнатная')], max_length=50, verbose_name='Категория')),
                ('path', models.CharField(blank=True, max_length=100, verbose_name='Путь')),
                ('floor_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество этажей')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
                ('path', models.CharField(default='', max_length=100, verbose_name='Путь')),
                ('new_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для новостройки')),
                ('new_desc', models.TextField(blank=True, null=True, verbose_name='Описание для новостройки')),
                ('plot_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для застройки')),
                ('plot_desc', models.TextField(blank=True, null=True, verbose_name='Описание для застройки')),
                ('complex_card_bg', models.ImageField(blank=True, null=True, upload_to='cities/complexes/cards/', verbose_name='Фон карточки города для комплексов')),
                ('complex_bg', models.ImageField(blank=True, null=True, upload_to='cities/complexes/bg/', verbose_name='Фон для комплексов')),
                ('plot_card_bg', models.ImageField(blank=True, null=True, upload_to='cities/plots/cards/', verbose_name='Фон карточки города для застроек')),
                ('plot_bg', models.ImageField(blank=True, null=True, upload_to='cities/plots/bg/', verbose_name='Фон для застроек')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название комплекса')),
                ('path', models.CharField(default='', max_length=100, verbose_name='Путь')),
                ('card_bg', models.ImageField(blank=True, null=True, upload_to='complexes/cards/', verbose_name='Фон карточки в слайдере')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complexes', to='ark.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Комплекс',
                'verbose_name_plural': 'Комплексы',
            },
        ),
        migrations.CreateModel(
            name='DynamicFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название формы')),
                ('data', models.JSONField(verbose_name='Данные формы')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Отправка формы',
                'verbose_name_plural': 'Отправки форм',
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=200, verbose_name='Район')),
                ('path', models.CharField(default='', max_length=100, verbose_name='Путь')),
                ('card_bg', models.ImageField(blank=True, null=True, upload_to='plots/cards/', verbose_name='Фон карточки в слайдере')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='ark.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Застройка',
                'verbose_name_plural': 'Застройки',
            },
        ),
        migrations.CreateModel(
            name='PlotLand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_type', models.CharField(choices=[('SNT', 'СНТ'), ('IJS', 'ИЖС')], max_length=3, verbose_name='Тип участка')),
                ('area', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Площадь участка (в сотках)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за участок')),
                ('path', models.CharField(blank=True, max_length=100, verbose_name='Путь')),
                ('gas', models.CharField(choices=[('да', 'Да'), ('нет', 'Нет'), ('возможность', 'Есть возможность подключения')], default='нет', max_length=20, verbose_name='Газ')),
                ('electricity', models.CharField(choices=[('да', 'Да'), ('нет', 'Нет'), ('возможность', 'Есть возможность подключения')], default='нет', max_length=20, verbose_name='Свет')),
                ('water', models.CharField(choices=[('да', 'Да'), ('нет', 'Нет'), ('возможность', 'Есть возможность подключения')], default='нет', max_length=20, verbose_name='Вода')),
                ('sewage', models.CharField(choices=[('да', 'Да'), ('нет', 'Нет'), ('возможность', 'Есть возможность подключения')], default='нет', max_length=20, verbose_name='Стоки')),
                ('developed', models.BooleanField(default=False, verbose_name='Разработан')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='plots/lands/', verbose_name='Изображение 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='plots/lands/', verbose_name='Изображение 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='plots/lands/', verbose_name='Изображение 3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='plots/lands/', verbose_name='Изображение 4')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='plots/lands/', verbose_name='Изображение 5')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='ark.plot', verbose_name='Застройка')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
            },
        ),
        migrations.CreateModel(
            name='PlotSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('desc_1', models.TextField(blank=True, null=True, verbose_name='Описание 1')),
                ('desc_2', models.TextField(blank=True, null=True, verbose_name='Описание 2')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='plot_sections/', verbose_name='Изображение 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='plot_sections/', verbose_name='Изображение 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='plot_sections/', verbose_name='Изображение 3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='plot_sections/', verbose_name='Изображение 4')),
                ('loc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Локация')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_sections', to='ark.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Секция застроек',
                'verbose_name_plural': 'Секции застроек',
            },
        ),
        migrations.CreateModel(
            name='PlotLandSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название секции')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('area', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Площадь')),
                ('land_status', models.CharField(choices=[('privatized', 'Приватизированный'), ('settlement', 'Земли населенных пунктов')], default='privatized', max_length=20, verbose_name='Статус земли')),
                ('gas', models.CharField(choices=[('да', 'Да'), ('нет', 'Нет'), ('возможность', 'Есть возможность подключения')], default='нет', max_length=20, verbose_name='Газ')),
                ('electricity', models.CharField(choices=[('да', 'Да'), ('нет', 'Нет'), ('возможность', 'Есть возможность подключения')], default='нет', max_length=20, verbose_name='Свет')),
                ('water', models.CharField(choices=[('да', 'Да'), ('нет', 'Нет'), ('возможность', 'Есть возможность подключения')], default='нет', max_length=20, verbose_name='Вода')),
                ('sewage', models.CharField(choices=[('да', 'Да'), ('нет', 'Нет'), ('возможность', 'Есть возможность подключения')], default='нет', max_length=20, verbose_name='Стоки')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='plot_land_sections/', verbose_name='Изображение 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='plot_land_sections/', verbose_name='Изображение 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='plot_land_sections/', verbose_name='Изображение 3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='plot_land_sections/', verbose_name='Изображение 4')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='plot_land_sections/', verbose_name='Изображение 5')),
                ('plot_land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ark.plotland', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Секция участка',
                'verbose_name_plural': 'Секции участков',
            },
        ),
        migrations.CreateModel(
            name='PlotLandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('image_type', models.CharField(blank=True, choices=[('slider_image', 'Картинка для слайдера'), ('additional_image', 'Дополнительное изображение')], max_length=20, null=True, verbose_name='Тип изображения')),
                ('plot_land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ark.plotland', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Изображение участка',
                'verbose_name_plural': 'Изображения участков',
            },
        ),
        migrations.CreateModel(
            name='PlotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('image_type', models.CharField(blank=True, choices=[('slider_image', 'Картинка для слайдера'), ('additional_image', 'Дополнительное изображение')], max_length=20, null=True, verbose_name='Тип изображения')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ark.plot', verbose_name='Застройка')),
            ],
            options={
                'verbose_name': 'Изображение застройки',
                'verbose_name_plural': 'Изображения застроек',
            },
        ),
        migrations.CreateModel(
            name='NewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('desc_1', models.TextField(blank=True, null=True, verbose_name='Описание 1')),
                ('desc_2', models.TextField(blank=True, null=True, verbose_name='Описание 2')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='new_sections/', verbose_name='Изображение 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='new_sections/', verbose_name='Изображение 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='new_sections/', verbose_name='Изображение 3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='new_sections/', verbose_name='Изображение 4')),
                ('loc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Локация')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_sections', to='ark.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Секция новостроек',
                'verbose_name_plural': 'Секции новостроек',
            },
        ),
        migrations.CreateModel(
            name='ComplexImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('image_type', models.CharField(blank=True, choices=[('slider_image', 'Картинка для слайдера'), ('additional_image', 'Дополнительное изображение')], max_length=20, null=True, verbose_name='Тип изображения')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ark.complex', verbose_name='Комплекс')),
            ],
            options={
                'verbose_name': 'Изображение комплекса',
                'verbose_name_plural': 'Изображения комплексов',
            },
        ),
        migrations.CreateModel(
            name='ApartmentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название секции')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('room_count', models.PositiveIntegerField(verbose_name='Количество комнат')),
                ('apartment_number', models.CharField(max_length=10, verbose_name='Номер квартиры')),
                ('area', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Площадь')),
                ('delivery_date', models.DateField(verbose_name='Срок сдачи')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='apartments/sections/', verbose_name='Изображение 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='apartments/sections/', verbose_name='Изображение 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='apartments/sections/', verbose_name='Изображение 3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='apartments/sections/', verbose_name='Изображение 4')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='apartments/sections/', verbose_name='Изображение 5')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ark.apartment', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Секция квартиры',
                'verbose_name_plural': 'Секции квартир',
            },
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('image_type', models.CharField(blank=True, choices=[('slider_image', 'Картинка для слайдера'), ('additional_image', 'Дополнительное изображение')], max_length=20, null=True, verbose_name='Тип изображения')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ark.apartment', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Изображение квартиры',
                'verbose_name_plural': 'Изображения квартир',
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='ark.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='ark.complex', verbose_name='Комплекс'),
        ),
    ]
