# Generated by Django 5.0.4 on 2024-09-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ark", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="path",
            field=models.CharField(max_length=100, verbose_name="Путь"),
        ),
        migrations.AlterField(
            model_name="complex",
            name="path",
            field=models.CharField(max_length=100, verbose_name="Путь"),
        ),
        migrations.AlterField(
            model_name="plot",
            name="district",
            field=models.CharField(max_length=200, verbose_name="Район"),
        ),
        migrations.AlterField(
            model_name="plot",
            name="path",
            field=models.CharField(max_length=100, verbose_name="Путь"),
        ),
        migrations.AlterField(
            model_name="plotland",
            name="path",
            field=models.CharField(max_length=100, verbose_name="Путь"),
        ),
    ]
