# Generated by Django 5.0.4 on 2024-09-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ark", "0003_alter_apartmentsection_apartment_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentimage",
            name="image_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("slider_image", "Картинка для слайдера"),
                    ("additional_image", "Дополнительное изображение"),
                ],
                max_length=40,
                null=True,
                verbose_name="Тип изображения",
            ),
        ),
        migrations.AlterField(
            model_name="complex",
            name="name",
            field=models.CharField(max_length=400, verbose_name="Название комплекса"),
        ),
        migrations.AlterField(
            model_name="compleximage",
            name="image_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("slider_image", "Картинка для слайдера"),
                    ("additional_image", "Дополнительное изображение"),
                ],
                max_length=40,
                null=True,
                verbose_name="Тип изображения",
            ),
        ),
        migrations.AlterField(
            model_name="plot",
            name="district",
            field=models.CharField(max_length=400, verbose_name="Район"),
        ),
        migrations.AlterField(
            model_name="plotimage",
            name="image_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("slider_image", "Картинка для слайдера"),
                    ("additional_image", "Дополнительное изображение"),
                ],
                max_length=40,
                null=True,
                verbose_name="Тип изображения",
            ),
        ),
        migrations.AlterField(
            model_name="plotland",
            name="electricity",
            field=models.CharField(
                choices=[
                    ("да", "Да"),
                    ("нет", "Нет"),
                    ("Есть возможность подключения", "Есть возможность подключения"),
                ],
                default="нет",
                max_length=40,
                verbose_name="Свет",
            ),
        ),
        migrations.AlterField(
            model_name="plotland",
            name="gas",
            field=models.CharField(
                choices=[
                    ("да", "Да"),
                    ("нет", "Нет"),
                    ("Есть возможность подключения", "Есть возможность подключения"),
                ],
                default="нет",
                max_length=40,
                verbose_name="Газ",
            ),
        ),
        migrations.AlterField(
            model_name="plotland",
            name="sewage",
            field=models.CharField(
                choices=[
                    ("да", "Да"),
                    ("нет", "Нет"),
                    ("Есть возможность подключения", "Есть возможность подключения"),
                ],
                default="нет",
                max_length=40,
                verbose_name="Стоки",
            ),
        ),
        migrations.AlterField(
            model_name="plotland",
            name="water",
            field=models.CharField(
                choices=[
                    ("да", "Да"),
                    ("нет", "Нет"),
                    ("Есть возможность подключения", "Есть возможность подключения"),
                ],
                default="нет",
                max_length=40,
                verbose_name="Вода",
            ),
        ),
        migrations.AlterField(
            model_name="plotlandimage",
            name="image_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("slider_image", "Картинка для слайдера"),
                    ("additional_image", "Дополнительное изображение"),
                ],
                max_length=40,
                null=True,
                verbose_name="Тип изображения",
            ),
        ),
        migrations.AlterField(
            model_name="plotlandsection",
            name="electricity",
            field=models.CharField(
                choices=[
                    ("да", "Да"),
                    ("нет", "Нет"),
                    ("Есть возможность подключения", "Есть возможность подключения"),
                ],
                default="нет",
                max_length=40,
                verbose_name="Свет",
            ),
        ),
        migrations.AlterField(
            model_name="plotlandsection",
            name="gas",
            field=models.CharField(
                choices=[
                    ("да", "Да"),
                    ("нет", "Нет"),
                    ("Есть возможность подключения", "Есть возможность подключения"),
                ],
                default="нет",
                max_length=40,
                verbose_name="Газ",
            ),
        ),
        migrations.AlterField(
            model_name="plotlandsection",
            name="land_status",
            field=models.CharField(
                choices=[
                    ("privatized", "Приватизированный"),
                    ("settlement", "Земли населенных пунктов"),
                ],
                default="privatized",
                max_length=40,
                verbose_name="Статус земли",
            ),
        ),
        migrations.AlterField(
            model_name="plotlandsection",
            name="sewage",
            field=models.CharField(
                choices=[
                    ("да", "Да"),
                    ("нет", "Нет"),
                    ("Есть возможность подключения", "Есть возможность подключения"),
                ],
                default="нет",
                max_length=40,
                verbose_name="Стоки",
            ),
        ),
        migrations.AlterField(
            model_name="plotlandsection",
            name="water",
            field=models.CharField(
                choices=[
                    ("да", "Да"),
                    ("нет", "Нет"),
                    ("Есть возможность подключения", "Есть возможность подключения"),
                ],
                default="нет",
                max_length=40,
                verbose_name="Вода",
            ),
        ),
    ]
