# Generated by Django 5.0.4 on 2024-09-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ark", "0004_alter_apartmentimage_image_type_alter_complex_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complex",
            name="desk",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="plot",
            name="desk",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
    ]
