# Generated by Django 5.0.4 on 2024-09-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ark", "0005_complex_desk_plot_desk"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="apartment",
            unique_together={("complex", "path")},
        ),
        migrations.AlterUniqueTogether(
            name="complex",
            unique_together={("city", "path")},
        ),
        migrations.AlterUniqueTogether(
            name="plot",
            unique_together={("city", "path")},
        ),
        migrations.AlterUniqueTogether(
            name="plotland",
            unique_together={("plot", "path")},
        ),
    ]
