# Generated by Django 5.0.7 on 2024-08-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new_buildings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newbuilding",
            options={
                "verbose_name": "Новостройка",
                "verbose_name_plural": "Новостройки",
            },
        ),
    ]
