# Generated by Django 5.0.7 on 2024-08-06 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new_buildings", "0002_alter_newbuilding_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newbuilding",
            options={
                "verbose_name": "Новостройки",
                "verbose_name_plural": "Новостройки",
            },
        ),
    ]
