version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    volumes:
      - ./backend:/opt/backend
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    ports:
      - "3000:3000"

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Копируем конфигурацию Nginx
    depends_on:
      - web
      - frontend
    networks:
      - webnet

volumes:
  pgdata:

networks:
  webnet:
    driver: bridge
