# Generated by Django 4.1 on 2024-09-02 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("studio", "Студия"),
                            ("one_bedroom", "Однокомнатная"),
                            ("two_bedroom", "Двухкомнатная"),
                            ("three_bedroom", "Трехкомнатная"),
                        ],
                        max_length=50,
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Квартира",
                "verbose_name_plural": "Квартиры",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название города"),
                ),
                (
                    "path",
                    models.CharField(default="", max_length=100, verbose_name="Путь"),
                ),
                (
                    "new_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Заголовок для новостройки",
                    ),
                ),
                (
                    "new_desc",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание для новостройки"
                    ),
                ),
                (
                    "plot_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Заголовок для застройки",
                    ),
                ),
                (
                    "plot_desc",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание для застройки"
                    ),
                ),
                (
                    "complex_card_bg",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cities/complexes/cards/",
                        verbose_name="Фон карточки города для комплексов",
                    ),
                ),
                (
                    "complex_bg",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cities/complexes/bg/",
                        verbose_name="Фон для комплексов",
                    ),
                ),
                (
                    "plot_card_bg",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cities/plots/cards/",
                        verbose_name="Фон карточки города для застроек",
                    ),
                ),
                (
                    "plot_bg",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cities/plots/bg/",
                        verbose_name="Фон для застроек",
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
        migrations.CreateModel(
            name="Complex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название комплекса"),
                ),
                (
                    "path",
                    models.CharField(default="", max_length=100, verbose_name="Путь"),
                ),
                (
                    "card_bg",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="complexes/cards/",
                        verbose_name="Фон карточки в слайдере",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complexes",
                        to="arc.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комплекс",
                "verbose_name_plural": "Комплексы",
            },
        ),
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "district",
                    models.CharField(blank=True, max_length=200, verbose_name="Район"),
                ),
                (
                    "path",
                    models.CharField(default="", max_length=100, verbose_name="Путь"),
                ),
                (
                    "card_bg",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="plots/cards/",
                        verbose_name="Фон карточки в слайдере",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plots",
                        to="arc.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Застройка",
                "verbose_name_plural": "Застройки",
            },
        ),
        migrations.CreateModel(
            name="PlotSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "desc_1",
                    models.TextField(blank=True, null=True, verbose_name="Описание 1"),
                ),
                (
                    "desc_2",
                    models.TextField(blank=True, null=True, verbose_name="Описание 2"),
                ),
                (
                    "image_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="plot_sections/",
                        verbose_name="Изображение 1",
                    ),
                ),
                (
                    "image_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="plot_sections/",
                        verbose_name="Изображение 2",
                    ),
                ),
                (
                    "image_3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="plot_sections/",
                        verbose_name="Изображение 3",
                    ),
                ),
                (
                    "image_4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="plot_sections/",
                        verbose_name="Изображение 4",
                    ),
                ),
                (
                    "loc",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Локация"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plot_sections",
                        to="arc.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Секция застроек",
                "verbose_name_plural": "Секции застроек",
            },
        ),
        migrations.CreateModel(
            name="PlotLand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "land_type",
                    models.CharField(
                        choices=[
                            ("6", "6 соток"),
                            ("8", "8 соток"),
                            ("10", "10 соток"),
                            ("12", "12 соток"),
                        ],
                        max_length=2,
                        verbose_name="Тип участка",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена за участок"
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lands",
                        to="arc.plot",
                        verbose_name="Застройка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участок",
                "verbose_name_plural": "Участки",
            },
        ),
        migrations.CreateModel(
            name="PlotImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="images/", verbose_name="Изображение"),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("slider_image", "Картинка для слайдера"),
                            ("additional_image", "Дополнительное изображение"),
                        ],
                        max_length=20,
                        verbose_name="Тип изображения",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="arc.plot",
                        verbose_name="Застройка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение застройки",
                "verbose_name_plural": "Изображения застроек",
            },
        ),
        migrations.CreateModel(
            name="NewSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "desc_1",
                    models.TextField(blank=True, null=True, verbose_name="Описание 1"),
                ),
                (
                    "desc_2",
                    models.TextField(blank=True, null=True, verbose_name="Описание 2"),
                ),
                (
                    "image_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="new_sections/",
                        verbose_name="Изображение 1",
                    ),
                ),
                (
                    "image_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="new_sections/",
                        verbose_name="Изображение 2",
                    ),
                ),
                (
                    "image_3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="new_sections/",
                        verbose_name="Изображение 3",
                    ),
                ),
                (
                    "image_4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="new_sections/",
                        verbose_name="Изображение 4",
                    ),
                ),
                (
                    "loc",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Локация"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_sections",
                        to="arc.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Секция новостроек",
                "verbose_name_plural": "Секции новостроек",
            },
        ),
        migrations.CreateModel(
            name="ComplexImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="images/", verbose_name="Изображение"),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("slider_image", "Картинка для слайдера"),
                            ("additional_image", "Дополнительное изображение"),
                        ],
                        max_length=20,
                        verbose_name="Тип изображения",
                    ),
                ),
                (
                    "complex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="arc.complex",
                        verbose_name="Комплекс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение комплекса",
                "verbose_name_plural": "Изображения комплексов",
            },
        ),
        migrations.CreateModel(
            name="ApartmentSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название секции"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                ("floor", models.PositiveIntegerField(verbose_name="Этаж")),
                (
                    "room_count",
                    models.PositiveIntegerField(verbose_name="Количество комнат"),
                ),
                (
                    "apartment_number",
                    models.CharField(max_length=10, verbose_name="Номер квартиры"),
                ),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Площадь"
                    ),
                ),
                ("delivery_date", models.DateField(verbose_name="Срок сдачи")),
                (
                    "image_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="apartments/sections/",
                        verbose_name="Изображение 1",
                    ),
                ),
                (
                    "image_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="apartments/sections/",
                        verbose_name="Изображение 2",
                    ),
                ),
                (
                    "image_3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="apartments/sections/",
                        verbose_name="Изображение 3",
                    ),
                ),
                (
                    "image_4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="apartments/sections/",
                        verbose_name="Изображение 4",
                    ),
                ),
                (
                    "image_5",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="apartments/sections/",
                        verbose_name="Изображение 5",
                    ),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="arc.apartment",
                        verbose_name="Квартира",
                    ),
                ),
            ],
            options={
                "verbose_name": "Секция квартиры",
                "verbose_name_plural": "Секции квартир",
            },
        ),
        migrations.CreateModel(
            name="ApartmentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="images/", verbose_name="Изображение"),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("slider_image", "Картинка для слайдера"),
                            ("additional_image", "Дополнительное изображение"),
                        ],
                        max_length=20,
                        verbose_name="Тип изображения",
                    ),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="arc.apartment",
                        verbose_name="Квартира",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение квартиры",
                "verbose_name_plural": "Изображения квартир",
            },
        ),
        migrations.AddField(
            model_name="apartment",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apartments",
                to="arc.city",
                verbose_name="Город",
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="complex",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apartments",
                to="arc.complex",
                verbose_name="Комплекс",
            ),
        ),
    ]
