# Generated by Django 5.0.7 on 2024-08-27 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название города"),
                ),
                (
                    "path",
                    models.CharField(default="", max_length=100, verbose_name="Путь"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cities/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Заголовок"
                    ),
                ),
                (
                    "desc",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
        migrations.CreateModel(
            name="Complex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название комплекса"),
                ),
                (
                    "path",
                    models.CharField(default="", max_length=100, verbose_name="Путь"),
                ),
                (
                    "studia",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество студий"
                    ),
                ),
                (
                    "one",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество 1-комнатных квартир"
                    ),
                ),
                (
                    "two",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество 2-комнатных квартир"
                    ),
                ),
                (
                    "three",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество 3-комнатных квартир"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complexes",
                        to="arc.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комплекс",
                "verbose_name_plural": "Комплексы",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "desc",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "image_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sections/",
                        verbose_name="Изображение 1",
                    ),
                ),
                (
                    "image_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sections/",
                        verbose_name="Изображение 2",
                    ),
                ),
                (
                    "image_3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sections/",
                        verbose_name="Изображение 3",
                    ),
                ),
                (
                    "loc",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Локация"
                    ),
                ),
                (
                    "complex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="arc.complex",
                        verbose_name="Комплекс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Секция",
                "verbose_name_plural": "Секции",
            },
        ),
    ]
