# Generated by Django 5.0.7 on 2024-08-28 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="complex",
        ),
        migrations.AddField(
            model_name="section",
            name="city",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="arc.city",
                verbose_name="Город",
            ),
            preserve_default=False,
        ),
    ]
