# Generated by Django 4.1 on 2024-09-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0002_apartment_path_plotland_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="category",
            field=models.CharField(
                choices=[
                    ("studio", "Студия"),
                    ("one_room", "Однокомнатная"),
                    ("two_room", "Двухкомнатная"),
                    ("three_room", "Трехкомнатная"),
                ],
                max_length=50,
                verbose_name="Категория",
            ),
        ),
    ]
