# Generated by Django 5.0.7 on 2024-08-30 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0002_remove_section_complex_section_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "district",
                    models.CharField(blank=True, max_length=200, verbose_name="Район"),
                ),
                (
                    "path",
                    models.CharField(default="", max_length=100, verbose_name="Путь"),
                ),
                (
                    "field_1",
                    models.TextField(blank=True, null=True, verbose_name="Field 1"),
                ),
                (
                    "field_2",
                    models.TextField(blank=True, null=True, verbose_name="Field 2"),
                ),
                (
                    "field_3",
                    models.TextField(blank=True, null=True, verbose_name="Field 3"),
                ),
                (
                    "field_4",
                    models.TextField(blank=True, null=True, verbose_name="Field 4"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plots",
                        to="arc.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Застройка",
                "verbose_name_plural": "Застройки",
            },
        ),
    ]
