# Generated by Django 5.0.7 on 2024-08-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0003_plot"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="new_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Текст для новостройки"
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="plot_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Текст для застройки"
            ),
        ),
    ]
