# Generated by Django 4.1 on 2024-09-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0003_alter_apartment_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="path",
            field=models.CharField(blank=True, max_length=100, verbose_name="Путь"),
        ),
        migrations.AlterField(
            model_name="plotland",
            name="path",
            field=models.CharField(blank=True, max_length=100, verbose_name="Путь"),
        ),
    ]
