# Generated by Django 5.0.7 on 2024-08-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0004_city_new_text_city_plot_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="new_text",
        ),
        migrations.RemoveField(
            model_name="city",
            name="plot_text",
        ),
        migrations.AddField(
            model_name="city",
            name="new_desc",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание для новостройки"
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="new_title",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Заголовок для новостройки",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="plot_desc",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание для застройки"
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="plot_title",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Заголовок для застройки",
            ),
        ),
    ]
