# Generated by Django 4.1 on 2024-09-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0004_alter_apartment_path_alter_plotland_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="floor_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Количество этажей"
            ),
        ),
    ]
