# Generated by Django 4.1 on 2024-09-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0005_apartment_floor_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotland",
            name="developed",
            field=models.BooleanField(default=False, verbose_name="Разработан"),
        ),
        migrations.AddField(
            model_name="plotland",
            name="electricity",
            field=models.CharField(
                choices=[
                    ("да", "Да"),
                    ("нет", "Нет"),
                    ("возможность", "Есть возможность подключения"),
                ],
                default="нет",
                max_length=20,
                verbose_name="Свет",
            ),
        ),
        migrations.AddField(
            model_name="plotland",
            name="gas",
            field=models.CharField(
                choices=[
                    ("да", "Да"),
                    ("нет", "Нет"),
                    ("возможность", "Есть возможность подключения"),
                ],
                default="нет",
                max_length=20,
                verbose_name="Газ",
            ),
        ),
        migrations.AddField(
            model_name="plotland",
            name="sewage",
            field=models.CharField(
                choices=[
                    ("да", "Да"),
                    ("нет", "Нет"),
                    ("возможность", "Есть возможность подключения"),
                ],
                default="нет",
                max_length=20,
                verbose_name="Стоки",
            ),
        ),
        migrations.AddField(
            model_name="plotland",
            name="water",
            field=models.CharField(
                choices=[
                    ("да", "Да"),
                    ("нет", "Нет"),
                    ("возможность", "Есть возможность подключения"),
                ],
                default="нет",
                max_length=20,
                verbose_name="Вода",
            ),
        ),
        migrations.AlterField(
            model_name="plotland",
            name="land_type",
            field=models.CharField(
                choices=[("SNT", "СНТ"), ("IJS", "ИЖС")],
                max_length=3,
                verbose_name="Тип участка",
            ),
        ),
    ]
