# Generated by Django 5.0.7 on 2024-08-30 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0006_remove_city_desc_remove_city_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plot",
            name="field_1",
        ),
        migrations.RemoveField(
            model_name="plot",
            name="field_2",
        ),
        migrations.RemoveField(
            model_name="plot",
            name="field_3",
        ),
        migrations.RemoveField(
            model_name="plot",
            name="field_4",
        ),
    ]
