# Generated by Django 5.0.7 on 2024-08-30 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0007_remove_plot_field_1_remove_plot_field_2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("studio", "Студия"),
                            ("one_room", "Однокомнатная"),
                            ("two_rooms", "Двухкомнатная"),
                            ("three_rooms", "Трехкомнатная"),
                        ],
                        max_length=20,
                        verbose_name="Категория квартиры",
                    ),
                ),
                (
                    "floor_plan",
                    models.ImageField(
                        upload_to="apartments/floor_plans/",
                        verbose_name="Схема квартиры",
                    ),
                ),
                (
                    "slider_images",
                    models.ImageField(
                        upload_to="apartments/slider_images/",
                        verbose_name="Картинки для слайдера",
                    ),
                ),
                (
                    "complex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartments",
                        to="arc.complex",
                        verbose_name="Комплекс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Квартира",
                "verbose_name_plural": "Квартиры",
            },
        ),
    ]
