# Generated by Django 4.1 on 2024-09-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0008_plotland_image_1_plotland_image_2_plotland_image_3_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя, фамилия")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Адрес эл. почты"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("path", models.CharField(max_length=255, verbose_name="Путь")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата заявки"),
                ),
            ],
        ),
    ]
