# Generated by Django 5.0.7 on 2024-08-30 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0009_image_alter_apartment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apartment",
            options={"verbose_name": "Квартира", "verbose_name_plural": "Квартиры"},
        ),
        migrations.AlterModelOptions(
            name="image",
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
        migrations.AlterField(
            model_name="apartment",
            name="category",
            field=models.CharField(
                choices=[
                    ("studio", "Студия"),
                    ("one_bedroom", "Однокомнатная"),
                    ("two_bedroom", "Двухкомнатная"),
                    ("three_bedroom", "Трехкомнатная"),
                ],
                max_length=20,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="complex",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apartments",
                to="arc.complex",
                verbose_name="Комплекс",
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="floor_plan",
            field=models.ManyToManyField(
                related_name="apartments_floor_plans",
                to="arc.image",
                verbose_name="Схема квартиры",
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="slider_images",
            field=models.ManyToManyField(
                related_name="apartments_slider_images",
                to="arc.image",
                verbose_name="Картинки для слайдера",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="description",
            field=models.CharField(blank=True, max_length=255, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="images/", verbose_name="Изображение"),
        ),
    ]
