# Generated by Django 4.1 on 2024-09-05 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0010_alter_contactrequest_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlotLandSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Площадь участка (в сотках)",
                    ),
                ),
                (
                    "gas",
                    models.CharField(
                        choices=[
                            ("да", "Да"),
                            ("нет", "Нет"),
                            ("возможность", "Есть возможность подключения"),
                        ],
                        default="нет",
                        max_length=20,
                        verbose_name="Газ",
                    ),
                ),
                (
                    "electricity",
                    models.CharField(
                        choices=[
                            ("да", "Да"),
                            ("нет", "Нет"),
                            ("возможность", "Есть возможность подключения"),
                        ],
                        default="нет",
                        max_length=20,
                        verbose_name="Свет",
                    ),
                ),
                (
                    "water",
                    models.CharField(
                        choices=[
                            ("да", "Да"),
                            ("нет", "Нет"),
                            ("возможность", "Есть возможность подключения"),
                        ],
                        default="нет",
                        max_length=20,
                        verbose_name="Вода",
                    ),
                ),
                (
                    "sewage",
                    models.CharField(
                        choices=[
                            ("да", "Да"),
                            ("нет", "Нет"),
                            ("возможность", "Есть возможность подключения"),
                        ],
                        default="нет",
                        max_length=20,
                        verbose_name="Канализация",
                    ),
                ),
                (
                    "image_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="plots/lands/sections/",
                        verbose_name="Изображение 1",
                    ),
                ),
                (
                    "image_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="plots/lands/sections/",
                        verbose_name="Изображение 2",
                    ),
                ),
                (
                    "image_3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="plots/lands/sections/",
                        verbose_name="Изображение 3",
                    ),
                ),
                (
                    "image_4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="plots/lands/sections/",
                        verbose_name="Изображение 4",
                    ),
                ),
                (
                    "image_5",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="plots/lands/sections/",
                        verbose_name="Изображение 5",
                    ),
                ),
                (
                    "plot_land",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="arc.plotland",
                        verbose_name="Участок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Секция участка",
                "verbose_name_plural": "Секции участков",
            },
        ),
    ]
