# Generated by Django 5.0.7 on 2024-08-30 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0010_alter_apartment_options_alter_image_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartment",
            name="floor_plan",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="slider_images",
        ),
        migrations.AlterModelOptions(
            name="apartment",
            options={},
        ),
        migrations.AlterField(
            model_name="apartment",
            name="category",
            field=models.CharField(
                choices=[
                    ("studio", "Студия"),
                    ("one_bedroom", "Однокомнатная"),
                    ("two_bedroom", "Двухкомнатная"),
                    ("three_bedroom", "Трехкомнатная"),
                ],
                max_length=50,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="complex",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apartments",
                to="arc.complex",
            ),
        ),
        migrations.CreateModel(
            name="ApartmentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="apartments/images/", verbose_name="Изображение"
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("floor_plan", "Схема квартиры"),
                            ("slider_image", "Картинка для слайдера"),
                        ],
                        max_length=20,
                        verbose_name="Тип изображения",
                    ),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="arc.apartment",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
