# Generated by Django 5.0.7 on 2024-08-30 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0011_remove_apartment_floor_plan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="complex",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apartments",
                to="arc.complex",
                verbose_name="Комплекс",
            ),
        ),
        migrations.AlterField(
            model_name="apartmentimage",
            name="apartment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="arc.apartment",
                verbose_name="Квартира",
            ),
        ),
    ]
