# Generated by Django 4.1 on 2024-09-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0011_plotlandsection"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotlandsection",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="Цена"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plotlandsection",
            name="title",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Название секции"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="plotlandsection",
            name="area",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Площадь (в сотках)"
            ),
        ),
        migrations.AlterField(
            model_name="plotlandsection",
            name="image_1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="plotland_sections/",
                verbose_name="Изображение 1",
            ),
        ),
        migrations.AlterField(
            model_name="plotlandsection",
            name="image_2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="plotland_sections/",
                verbose_name="Изображение 2",
            ),
        ),
        migrations.AlterField(
            model_name="plotlandsection",
            name="image_3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="plotland_sections/",
                verbose_name="Изображение 3",
            ),
        ),
        migrations.AlterField(
            model_name="plotlandsection",
            name="image_4",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="plotland_sections/",
                verbose_name="Изображение 4",
            ),
        ),
        migrations.AlterField(
            model_name="plotlandsection",
            name="image_5",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="plotland_sections/",
                verbose_name="Изображение 5",
            ),
        ),
        migrations.AlterField(
            model_name="plotlandsection",
            name="sewage",
            field=models.CharField(
                choices=[
                    ("да", "Да"),
                    ("нет", "Нет"),
                    ("возможность", "Есть возможность подключения"),
                ],
                default="нет",
                max_length=20,
                verbose_name="Стоки",
            ),
        ),
    ]
