# Generated by Django 5.0.7 on 2024-08-30 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0012_alter_apartment_complex_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apartment",
            options={"verbose_name": "Квартира", "verbose_name_plural": "Квартиры"},
        ),
        migrations.AlterModelOptions(
            name="apartmentimage",
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
    ]
