# Generated by Django 4.1 on 2024-09-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0012_plotlandsection_price_plotlandsection_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotlandsection",
            name="land_purpose",
            field=models.CharField(
                choices=[
                    ("сельхоз", "Сельскохозяйственное"),
                    ("жилое", "Жилое"),
                    ("коммерческое", "Коммерческое"),
                ],
                default=1,
                max_length=50,
                verbose_name="Назначение",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plotlandsection",
            name="land_status",
            field=models.CharField(
                choices=[("активен", "Активен"), ("неактивен", "Неактивен")],
                default=1,
                max_length=50,
                verbose_name="Статус земли",
            ),
            preserve_default=False,
        ),
    ]
