# Generated by Django 5.0.7 on 2024-09-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0013_alter_apartment_options_alter_apartmentimage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="bg",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="cities/bg/",
                verbose_name="Фон на странице города",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="card_bg",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="cities/cards/",
                verbose_name="Фон карточки в слайдере",
            ),
        ),
        migrations.AddField(
            model_name="complex",
            name="bg",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="complexes/bg/",
                verbose_name="Фон на странице ЖК",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="image_4",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="sections/",
                verbose_name="Изображение 4",
            ),
        ),
    ]
