# Generated by Django 4.1 on 2024-09-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0013_plotlandsection_land_purpose_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plotlandsection",
            name="land_purpose",
        ),
        migrations.AlterField(
            model_name="plotlandsection",
            name="area",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Площадь"
            ),
        ),
        migrations.AlterField(
            model_name="plotlandsection",
            name="image_1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="plot_land_sections/",
                verbose_name="Изображение 1",
            ),
        ),
        migrations.AlterField(
            model_name="plotlandsection",
            name="image_2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="plot_land_sections/",
                verbose_name="Изображение 2",
            ),
        ),
        migrations.AlterField(
            model_name="plotlandsection",
            name="image_3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="plot_land_sections/",
                verbose_name="Изображение 3",
            ),
        ),
        migrations.AlterField(
            model_name="plotlandsection",
            name="image_4",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="plot_land_sections/",
                verbose_name="Изображение 4",
            ),
        ),
        migrations.AlterField(
            model_name="plotlandsection",
            name="image_5",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="plot_land_sections/",
                verbose_name="Изображение 5",
            ),
        ),
        migrations.AlterField(
            model_name="plotlandsection",
            name="land_status",
            field=models.CharField(
                choices=[
                    ("privatized", "Приватизированный"),
                    ("settlement", "Земли населенных пунктов"),
                ],
                default="privatized",
                max_length=20,
                verbose_name="Статус земли",
            ),
        ),
    ]
