# Generated by Django 5.0.7 on 2024-09-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0014_city_bg_city_card_bg_complex_bg_section_image_4"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="image",
        ),
    ]
