# Generated by Django 4.1 on 2024-09-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0014_remove_plotlandsection_land_purpose_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicFormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название формы"),
                ),
                ("data", models.JSONField(verbose_name="Данные формы")),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата отправки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Отправка формы",
                "verbose_name_plural": "Отправки форм",
            },
        ),
        migrations.DeleteModel(
            name="ContactRequest",
        ),
    ]
