# Generated by Django 5.0.7 on 2024-09-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0016_remove_section_desc_section_desc_1_section_desc_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="bg",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="plots/bg/",
                verbose_name="Фон на странице застройки",
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="card_bg",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="plots/cards/",
                verbose_name="Фон карточки в слайдере",
            ),
        ),
    ]
