# Generated by Django 5.0.7 on 2024-09-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0017_plot_bg_plot_card_bg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="bg",
        ),
        migrations.RemoveField(
            model_name="city",
            name="card_bg",
        ),
        migrations.AddField(
            model_name="city",
            name="complex_bg",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="cities/complexes/bg/",
                verbose_name="Фон для комплексов",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="complex_card_bg",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="cities/complexes/cards/",
                verbose_name="Фон карточки для комплексов",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="plot_bg",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="cities/plots/bg/",
                verbose_name="Фон для застроек",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="plot_card_bg",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="cities/plots/cards/",
                verbose_name="Фон карточки для застроек",
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="size_10",
            field=models.PositiveIntegerField(default=0, verbose_name="10 соток"),
        ),
        migrations.AddField(
            model_name="plot",
            name="size_12",
            field=models.PositiveIntegerField(default=0, verbose_name="12 соток"),
        ),
        migrations.AddField(
            model_name="plot",
            name="size_6",
            field=models.PositiveIntegerField(default=0, verbose_name="6 соток"),
        ),
        migrations.AddField(
            model_name="plot",
            name="size_8",
            field=models.PositiveIntegerField(default=0, verbose_name="8 соток"),
        ),
    ]
