# Generated by Django 5.0.7 on 2024-09-01 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0018_remove_city_bg_remove_city_card_bg_city_complex_bg_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlotLand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "land_type",
                    models.CharField(
                        choices=[
                            ("6", "6 соток"),
                            ("8", "8 соток"),
                            ("10", "10 соток"),
                            ("12", "12 соток"),
                        ],
                        max_length=2,
                        verbose_name="Тип участка",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена за участок"
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lands",
                        to="arc.plot",
                        verbose_name="Застройка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участок",
                "verbose_name_plural": "Участки",
            },
        ),
    ]
