# Generated by Django 5.0.7 on 2024-09-01 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0019_plotland"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "desc_1",
                    models.TextField(blank=True, null=True, verbose_name="Описание 1"),
                ),
                (
                    "desc_2",
                    models.TextField(blank=True, null=True, verbose_name="Описание 2"),
                ),
                (
                    "image_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="new_sections/",
                        verbose_name="Изображение 1",
                    ),
                ),
                (
                    "image_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="new_sections/",
                        verbose_name="Изображение 2",
                    ),
                ),
                (
                    "image_3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="new_sections/",
                        verbose_name="Изображение 3",
                    ),
                ),
                (
                    "image_4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="new_sections/",
                        verbose_name="Изображение 4",
                    ),
                ),
                (
                    "loc",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Локация"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_sections",
                        to="arc.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Секция новостроек",
                "verbose_name_plural": "Секции новостроек",
            },
        ),
        migrations.CreateModel(
            name="PlotSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "desc_1",
                    models.TextField(blank=True, null=True, verbose_name="Описание 1"),
                ),
                (
                    "desc_2",
                    models.TextField(blank=True, null=True, verbose_name="Описание 2"),
                ),
                (
                    "image_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="plot_sections/",
                        verbose_name="Изображение 1",
                    ),
                ),
                (
                    "image_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="plot_sections/",
                        verbose_name="Изображение 2",
                    ),
                ),
                (
                    "image_3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="plot_sections/",
                        verbose_name="Изображение 3",
                    ),
                ),
                (
                    "image_4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="plot_sections/",
                        verbose_name="Изображение 4",
                    ),
                ),
                (
                    "loc",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Локация"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plot_sections",
                        to="arc.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Секция застроек",
                "verbose_name_plural": "Секции застроек",
            },
        ),
    ]
