# Generated by Django 5.0.7 on 2024-09-01 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0020_newsection_plotsection"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Section",
        ),
    ]
