# Generated by Django 5.0.7 on 2024-09-01 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0021_delete_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="city",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apartments",
                to="arc.city",
                verbose_name="Город",
            ),
        ),
    ]
