# Generated by Django 5.0.7 on 2024-09-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0022_apartment_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complex",
            name="bg",
        ),
        migrations.RemoveField(
            model_name="plot",
            name="bg",
        ),
        migrations.AddField(
            model_name="complex",
            name="card_bg",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="complexes/cards/",
                verbose_name="Фон карточки слайдера",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="complex_card_bg",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="cities/complexes/cards/",
                verbose_name="Фон карточки города для комплексов",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="plot_card_bg",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="cities/plots/cards/",
                verbose_name="Фон карточки города для застроек",
            ),
        ),
    ]
