# Generated by Django 3.2.22 on 2024-09-02 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0023_remove_complex_bg_remove_plot_bg_complex_card_bg_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlotImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="images/", verbose_name="Изображение"),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("slider_image", "Картинка для слайдера"),
                            ("additional_image", "Дополнительное изображение"),
                        ],
                        max_length=20,
                        verbose_name="Тип изображения",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="arc.plot",
                        verbose_name="Застройка",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ComplexImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="images/", verbose_name="Изображение"),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("slider_image", "Картинка для слайдера"),
                            ("additional_image", "Дополнительное изображение"),
                        ],
                        max_length=20,
                        verbose_name="Тип изображения",
                    ),
                ),
                (
                    "complex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="arc.complex",
                        verbose_name="Комплекс",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
