# Generated by Django 3.2.22 on 2024-09-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0025_auto_20240902_2034"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compleximage",
            options={},
        ),
    ]
