# Generated by Django 3.2.22 on 2024-09-02 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("arc", "0026_alter_compleximage_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compleximage",
            options={
                "verbose_name": "Изображение комплекса",
                "verbose_name_plural": "Изображения комплексов",
            },
        ),
    ]
