# Generated by Django 3.2.22 on 2024-09-02 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0027_alter_compleximage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentimage',
            options={'verbose_name': 'Изображение квартиры', 'verbose_name_plural': 'Изображения квартир'},
        ),
        migrations.RemoveField(
            model_name='complex',
            name='one',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='studia',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='three',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='two',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='size_10',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='size_12',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='size_6',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='size_8',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='arc.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='apartmentimage',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='apartmentimage',
            name='image_type',
            field=models.CharField(choices=[('slider_image', 'Картинка для слайдера'), ('additional_image', 'Дополнительное изображение')], max_length=20, verbose_name='Тип изображения'),
        ),
        migrations.CreateModel(
            name='ApartmentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название секции')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('room_count', models.PositiveIntegerField(verbose_name='Количество комнат')),
                ('apartment_number', models.CharField(max_length=10, verbose_name='Номер квартиры')),
                ('area', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Площадь')),
                ('delivery_date', models.DateField(verbose_name='Срок сдачи')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='apartments/sections/', verbose_name='Изображение 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='apartments/sections/', verbose_name='Изображение 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='apartments/sections/', verbose_name='Изображение 3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='apartments/sections/', verbose_name='Изображение 4')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='apartments/sections/', verbose_name='Изображение 5')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='arc.apartment', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Секция квартиры',
                'verbose_name_plural': 'Секции квартир',
            },
        ),
    ]
