"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-1@b0tw9j$d$$w@=+weh)&lmk@ky=_h6l1(ua$g%b9ltgvymo^x"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "dom-ark.com",
    "www.dom-ark.com",
    "79.174.86.29",
]


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_yasg",
    "corsheaders",
    "clearcache",
    # "admin_reorder",
    "ark",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",  # Добавлено
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://arkcrimea.ru",
]


CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
            ],
        },
    },
]


WSGI_APPLICATION = "backend.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': os.getenv('POSTGRES_PORT'),
    }
}

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": "u2800927_arc",
#         "USER": "u2800927_root",
#         "PASSWORD": "123321qweewq",
#         "HOST": "arkcrimea.ru",
#         "PORT": "3306",
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = [
    ("ru", "Russian"),
]

LOCALE_PATHS = [os.path.join(BASE_DIR, "locale")]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/


STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


JAZZMIN_SETTINGS = {
    "site_title": "ARK Admin",
    "site_header": "ARK Админ панель",  # Разделены слова для лучшего отображения
    "site_brand": "ARK",
    "welcome_sign": "Добро пожаловать в ARK!",
    "copyright": "TOXIC TEAM",
    # "site_logo": "path/to/your/logo.png",  # На будущее: путь к вашему логотипу
    # "site_icon": "path/to/your/favicon.ico",  # На будущее: путь к вашему favicon
    "search_model": "ark.City",
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        # Группа: Города - Комплексы - Квартиры
        "ark.City",
        "ark.Complex",
        "ark.Apartment",
        "ark.NewSection",
        # Группа: Города - Застройки - Участки и Секции
        "ark.Plot",
        "ark.PlotLand",
        "ark.NewSection",
        "ark.PlotSection",
        # Другие модели
        "ark.DynamicFormSubmission",
        "auth",
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "ark.City": "fas fa-city",
        "ark.Complex": "fas fa-building",
        "ark.Apartment": "fas fa-home",
        "ark.Plot": "fas fa-map",
        "ark.PlotLand": "fas fa-map-marked",
        "ark.NewSection": "fas fa-layer-group",
        "ark.PlotSection": "fas fa-layer-group",
        "ark.DynamicFormSubmission": "fas fa-envelope",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": None,  # На будущее: путь к вашему кастомному CSS
    "custom_js": None,  # На будущее: путь к вашему кастомному JS
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    "language_chooser": True,  # Включает выбор языка в админке
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    # Вы можете изменить тему на другую, например, "flatly", "darkly", "cerulean", "cosmo", "cyborg", "darkly", "journal", "lumen", "paper", "sandstone", "simplex", "slate", "spacelab", "superhero", "united", "yeti"
    # "dark_mode_theme": "darkly",  # Тема для темного режима
    # Настройки навбара
    "navbar_small_text": False,
    "navbar_dark_mode": False,  # Установите True для темного навбара
    "navbar_fixed": True,  # Закрепить навбар при прокрутке
    # Настройки боковой панели
    "sidebar_fixed": True,  # Закрепить боковую панель при прокрутке
    "sidebar": "sidebar-dark-primary",
    # Цветовая схема боковой панели. Попробуйте "sidebar-light-primary" для светлой боковой панели
    # Настройки кнопок
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    # Настройки акцентов
    "accent": "accent-primary",
    # Настройки компоновки
    "body_small_text": False,
    "footer_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    # Другие настройки
    "no_navbar_border": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "sidebar_disable_hover": False,
    "actions_sticky_top": True,
    # "custom_css": "path/to/your/custom.css",  # На будущее: путь к вашему кастомному CSS
    # "custom_js": "path/to/your/custom.js",    # На будущее: путь к вашему кастомному JS
}
