# Generated by Django 5.0.7 on 2024-07-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0002_footer_alter_mainsection_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "bgr_image",
                    models.ImageField(blank=True, null=True, upload_to="content/"),
                ),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Section1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("desc", models.TextField(blank=True, null=True)),
                ("climate", models.CharField(max_length=255)),
                ("nature", models.CharField(max_length=255)),
                ("assessability", models.CharField(max_length=255)),
                ("infrastructure", models.CharField(max_length=255)),
                ("possibilities", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Section2Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.ImageField(upload_to="icons/")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("background", models.ImageField(upload_to="backgrounds/")),
                ("button_text", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Section3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="backgrounds/")),
                ("tg_link", models.URLField()),
                ("viber_link", models.URLField()),
                ("whatsup_link", models.URLField()),
                ("bgr_button", models.ImageField(upload_to="backgrounds/")),
            ],
        ),
        migrations.RenameField(
            model_name="header",
            old_name="header_background",
            new_name="bgr_bottom",
        ),
        migrations.RenameField(
            model_name="header",
            old_name="title",
            new_name="header_title",
        ),
        migrations.RenameField(
            model_name="header",
            old_name="logo",
            new_name="logo_icon",
        ),
        migrations.RemoveField(
            model_name="header",
            name="description",
        ),
        migrations.RemoveField(
            model_name="header",
            name="navigation_background_color",
        ),
        migrations.AddField(
            model_name="footer",
            name="color_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="footer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="footer",
            name="youtube_icon",
            field=models.ImageField(blank=True, null=True, upload_to="icons/"),
        ),
        migrations.AddField(
            model_name="header",
            name="header_bgr",
            field=models.ImageField(blank=True, null=True, upload_to="backgrounds/"),
        ),
        migrations.AddField(
            model_name="header",
            name="header_title_bottom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="header",
            name="nav_bgr",
            field=models.ImageField(blank=True, null=True, upload_to="backgrounds/"),
        ),
        migrations.CreateModel(
            name="Section2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("cards", models.ManyToManyField(to="main_page.section2card")),
            ],
        ),
        migrations.DeleteModel(
            name="Content",
        ),
        migrations.DeleteModel(
            name="MainSection",
        ),
    ]
