# Generated by Django 5.0.7 on 2024-08-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0006_maincontent_class_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="maincontent",
            name="content",
            field=models.TextField(default="", verbose_name="Контент"),
        ),
        migrations.AddField(
            model_name="maincontent",
            name="routes",
            field=models.JSONField(default=list, verbose_name="Маршруты"),
        ),
        migrations.AddField(
            model_name="maincontent",
            name="title",
            field=models.CharField(
                default="", max_length=255, verbose_name="Заголовок"
            ),
        ),
    ]
