# Generated by Django 5.0.7 on 2024-08-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0007_maincontent_content_maincontent_routes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maincontent",
            name="content",
        ),
        migrations.RemoveField(
            model_name="maincontent",
            name="routes",
        ),
        migrations.RemoveField(
            model_name="maincontent",
            name="title",
        ),
    ]
