# Generated by Django 5.0.7 on 2024-08-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_page",
            "0008_remove_maincontent_content_remove_maincontent_routes_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                ("link", models.URLField(verbose_name="Ссылка")),
                (
                    "image",
                    models.ImageField(upload_to="cards/", verbose_name="Изображение"),
                ),
            ],
            options={
                "verbose_name": "Карточка",
                "verbose_name_plural": "Карточки",
            },
        ),
        migrations.DeleteModel(
            name="SectionThree",
        ),
        migrations.DeleteModel(
            name="SectionTwo",
        ),
        migrations.DeleteModel(
            name="SectionTwoCard",
        ),
    ]
