# Generated by Django 5.0.7 on 2024-08-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0009_card_delete_sectionthree_delete_sectiontwo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="link",
        ),
        migrations.AddField(
            model_name="card",
            name="path",
            field=models.TextField(default=1, verbose_name="Путь"),
            preserve_default=False,
        ),
    ]
