# Generated by Django 5.0.7 on 2024-08-06 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0010_remove_card_link_card_path"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SectionOne",
            new_name="Advantages",
        ),
    ]
