# Generated by Django 5.0.7 on 2024-08-06 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0011_rename_sectionone_advantages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advantages",
            options={
                "ordering": ["title"],
                "verbose_name": "Преимущества",
                "verbose_name_plural": "Преимущества",
            },
        ),
        migrations.AlterModelOptions(
            name="card",
            options={
                "ordering": ["title"],
                "verbose_name": "Карточка",
                "verbose_name_plural": "Карточки",
            },
        ),
        migrations.AlterModelOptions(
            name="footer",
            options={
                "ordering": ["phone_number"],
                "verbose_name": "Футер",
                "verbose_name_plural": "Футеры",
            },
        ),
        migrations.AlterModelOptions(
            name="header",
            options={
                "ordering": ["header_title"],
                "verbose_name": "Заголовок",
                "verbose_name_plural": "Заголовки",
            },
        ),
        migrations.AlterModelOptions(
            name="maincontent",
            options={
                "ordering": ["name"],
                "verbose_name": "Основное содержание",
                "verbose_name_plural": "Основное содержание",
            },
        ),
    ]
