# Generated by Django 5.0.7 on 2024-08-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0012_alter_advantages_options_alter_card_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={
                "ordering": ["id"],
                "verbose_name": "Карточка",
                "verbose_name_plural": "Карточки",
            },
        ),
    ]
