# Generated by Django 5.0.7 on 2024-08-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0013_alter_card_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя, фамилия")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Адрес эл. почты"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "consent",
                    models.BooleanField(
                        default=False,
                        verbose_name="Согласие на обработку персональных данных",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контактная форма",
                "verbose_name_plural": "Контактные формы",
                "ordering": ["name"],
            },
        ),
    ]
