# Generated by Django 5.0.7 on 2024-08-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "image",
                    models.ImageField(upload_to="plots/", verbose_name="Изображение"),
                ),
                (
                    "location",
                    models.CharField(max_length=255, verbose_name="Местоположение"),
                ),
                ("area", models.CharField(max_length=100, verbose_name="Площадь")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("path", models.TextField(verbose_name="Путь")),
            ],
            options={
                "verbose_name": "Участок под застройку",
                "verbose_name_plural": "Участки под застройку",
            },
        ),
    ]
