# Generated by Django 5.0.7 on 2024-08-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plot_buildings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlotBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "bgr_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="plot_buildings/",
                        verbose_name="Фоновое изображение",
                    ),
                ),
                ("path", models.TextField(verbose_name="Путь")),
                (
                    "class_name",
                    models.CharField(
                        default="", max_length=100, verbose_name="Класс контента"
                    ),
                ),
            ],
            options={
                "verbose_name": "Участки застройки",
                "verbose_name_plural": "Участки застройки",
            },
        ),
        migrations.DeleteModel(
            name="Plot",
        ),
    ]
